name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pre-commit:
    uses: divkix/reusable-workflows/.github/workflows/pre-commit.yml@main

  automerge-dependabot-pr:
    name: Automerge Dependabot PRs
    # needs pre-commit job to finish and pass
    needs:
      - pre-commit
    # using reusable workflow
    uses: divkix/reusable-workflows/.github/workflows/automerge-dependabot-pr.yml@main
