name: Auto Merge Dependabot PR

on:
  workflow_call:
    inputs:
      target:
        type: string
        description: "Level of dependencies to update"
        default: "minor"
        required: false

jobs:
  automerge-dependabot-pr:
    if: github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.5.0
        with:
          target: ${{ inputs.target }}
