name: Auto Merge Dependabot PR

on:
  workflow_call:

jobs:
  automerge-dependabot-pr:
    if: github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.3.0
        with:
          target: minor
