name: Build and Test Python Package

on:
  workflow_call:
    inputs:
      tag:
        description: 'Tag to use tesing the package'
        default: '${{ github.sha }}'
        required: false
        type: string
      custom_commands:
        description: "Custom commands to run before building and testing"
        default: ""
        required: false
        type: string
      os:
        description: "Operating system to run on"
        default: "ubuntu-latest"
        required: false
        type: string
      python-version:
        description: "Python version to use"
        default: "3.10"
        required: false
        type: string

jobs:
  build-and-test:
    name: Build and Test Package
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.tag }}
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies & Configuring
        run: |-
          pip3 install --upgrade pip setuptools wheel
          pip3 install --upgrade poetry
          poetry config virtualenvs.create false
          poetry install
      - name: Run custom commands
        if: ${{ inputs.custom_commands != '' }}
        run: |-
          ${{ inputs.custom_commands }}
