name: Create a new release

on:
  workflow_call:
    inputs:
      tag:
        description: "The tag of the repository to checkout"
        required: true
        type: string
      body:
        description: "The body of the release"
        required: false
        type: string

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.tag }}
      - name: Set ENV Variables
        run: |-
          if [[ ${{ inputs.body }} == "" ]] ; then
            echo "BODY=${{ github.event.repository.name }} ${{ inputs.tag }}" >> $GITHUB_ENV
          else
            echo "BODY=${{ inputs.body }}" >> $GITHUB_ENV
          fi
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ inputs.tag }}
          tag_name: ${{ inputs.tag }}
          body: ${{ env.BODY }}
