name: Create a new release

on:
  workflow_call:
    inputs:
      tag:
        # tag to checkout
        description: "The tag of the repository to checkout"
        required: true
        type: string
      body:
        # body of the release
        description: "The body of the release"
        required: false
        type: string
        default: "Release ${{ inputs.tag }}"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # checkout the tag
          ref: ${{ inputs.tag }}
      - name: Release
        # create the release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ inputs.tag }}
          tag_name: ${{ inputs.tag }}
          body: ${{ inputs.body }}
