name: Get Repository Info

on:
  workflow_call:
    outputs:
      tag: 
        description: "The latest tag of the repository"
        value: ${{ jobs.get-repo-info.outputs.tag }}
      project_name:
        description: "The name of the repository (without the owner and lowercased)"
        value: ${{ jobs.get-repo-info.outputs.project_name }}
      repo_name: 
        description: "The name of the repository (with the owner and lowercased)"
        value: ${{ jobs.get-repo-info.outputs.repo_name }}

jobs:
  get-repo-info:
    name: Get Repo Info
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get Latest Tag
      id: get_tag
      run: |-
        tag="$(git tag | sort -V | tail -1)"
        echo "::set-output name=tag::$(git tag | sort -V | tail -1)"
    - name: Lowercase required vars
      id: lowercase
      run: |-
        echo "::set-output name=project_name::$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]')"
        echo "::set-output name=repo_name::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')"
    outputs:
      tag: ${{ steps.get_tag.outputs.tag }}
      project_name: ${{ steps.lowercase.outputs.project_name }}
      repo_name: ${{ steps.lowercase.outputs.repo_name }}
