name: Get Repository Info

on:
  workflow_call:
    outputs:
      # set 3 outputs, tag, project_name and repo_name
      tag:
        description: "The tag of the repository to checkout"
        value: ${{ jobs.get-repo-info.outputs.tag }}
      project_name:
        description: "The name of the repository (without the owner and lowercased)"
        value: ${{ jobs.get-repo-info.outputs.project_name }}
      repo_name:
        description: "The name of the repository (with the owner and lowercased)"
        value: ${{ jobs.get-repo-info.outputs.repo_name }}

jobs:
  get-repo-info:
    name: Get Repo Info
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get Latest Tag
        id: get_tag
        # get the latest tag from checking out the repo
        run: |-
          echo "tag=$(git tag | sort -V | tail -1)" >> $GITHUB_OUTPUT
      - name: Lowercase required vars
        # lowercase the project_name and repo_name
        id: lowercase
        run: |-
          echo "project_name=$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
          echo "repo_name=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
    # set the outputs
    outputs:
      tag: ${{ steps.get_tag.outputs.tag }}
      project_name: ${{ steps.lowercase.outputs.project_name }}
      repo_name: ${{ steps.lowercase.outputs.repo_name }}
