name: Goreleaser CI

on:
  workflow_call:
    inputs:
      use-upx:
        description: "Use UPX to compress the binaries"
        required: false
        type: boolean
        default: false
      upx-files:
        description: "Binaries to compress with UPX"
        required: false
        type: string
        default: "dist/**/**"

jobs:
  ci:
    name: Goreleaser CI
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "stable"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --snapshot --skip-publish --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run UPX
        if: ${{ inputs.use-upx }}
        continue-on-error: true
        uses: crazy-max/ghaction-upx@v2
        with:
          version: latest
          files: |
            ${{ inputs.upx-files }}
          args: -fq --brute
      - name: Tar files
        run: tar -cvf artifacts.tar dist/
      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: artifacts.tar
