name: Goreleaser CI

on:
  workflow_call:

jobs:
  ci:
    name: Goreleaser CI
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: actions/setup-go@v4
        with:
          go-version: "stable"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --snapshot --skip-publish --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run UPX
        continue-on-error: true
        uses: crazy-max/ghaction-upx@v2
        with:
          version: latest
          files: |
            dist/**/**
          args: -fq --brute
      - name: Tar files
        run: tar -cvf warp.tar dist/
      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: artifacts.tar
