name: Push to PyPI

on:
  workflow_call:
    inputs:
      tag:
        description: "The latest tag of the repository"
        required: true
        type: string
    secrets:
      PYPI_TOKEN:
        required: true

jobs:
  push-to-pypi:
    name: Push to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.tag }}
      - name: Publish python poetry package
        uses: JRubics/poetry-publish@v1.13
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
